### ISSUE TITLE
Error message "services.restart must be a mapping" when running docker-compose up

### ISSUE THREAD

**Issue by dikahariss** [formbricks/formbricks#223]
### Issue Summary

When running the command "docker-compose up -d" with the following docker-compose.yml file:

```
version: "3.3"
services:
  restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  formbricks:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres:
    driver: local
```

I get the following error message:
"services.restart must be a mapping"

I believe this error message is caused by the "restart: unless-stopped" option being defined at the wrong level in the docker-compose.yml file. According to the Docker Compose documentation, the "restart" option can only be defined at the service level, not at the top-level services.

To fix this issue, I moved the "restart: unless-stopped" option from the top-level services to each individual service in the docker-compose.yml file. However, I believe this error message could be more helpful in identifying the root cause of the issue.

```
version: "3.3"
services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres:
    driver: local
```

I'm running Docker Compose version v2.14.0 on Windows 11.

Thank you for your attention to this matter.
