### ISSUE TITLE
[BUG] Azure AD does not function out of the box, documentation is missing important steps

### ISSUE THREAD

**Issue by ag-gaphp** [formbricks/formbricks#2879]
### Issue Summary

Using the documentation, the Azure AD integration does not function. The documentation is missing steps and information for the redirect URL that is needed.

### Steps to Reproduce

1. Setup Azure Tenant according to the [Formbricks Docs](https://formbricks.com/docs/self-hosting/configuration#azure-sso-o-auth)
- _Observe_: Docs say to get your IDs from Azure (which is now called Microsoft Entra ID), but the Client Secret doesn't exist without first [creating a new App Registration](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-app-sign-user-app-registration?tabs=aspnetcore#register-an-app-by-using-the-azure-portal). Then you can generate a new Client Secret to use.
2. Input the Client ID/Secret and Tenant ID to Formbricks
3. Disable all other authentication methods
4. Spin up the Formbricks service, then go to the URL for the setup wizard
5. Attempt to sign-in using Azure
- _Observe_: Microsoft error stating that a reply address is missing
![image](https://github.com/formbricks/formbricks/assets/164041490/780bae9c-bca5-4b2d-ba78-8c6bf7ee13ca)

### Expected behavior

The documentation outlines all the necessary steps for setting up an Azure Tenant, especially including the important steps for:
* Registering a new app
* Generating a client secret
* Where to find your client ID and tenant ID
* Adding a redirect URL

Otherwise, I would expect the login to succeed as long as I copy and pasted my secrets properly and followed the documentation exactly.

### Other information

The Microsoft error is specifically referring to a Redirect URL that is needed. I have several other Azure AD OAuth integrations in place, and they all require a unique redirect URL. The docs do not mention what this redirect URL should be anywhere.

[More info from Microsoft in this answer](https://learn.microsoft.com/en-us/answers/questions/183594/aadsts500113-no-reply-address-is-registered-for-th)

I should also note that I am using a simplified Docker Compose setup with a .env file:

```yml
services:

  db:
    image: postgres:alpine
    container_name: formbricks-db
    environment:
      POSTGRES_DB: formbricks
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_USER: formbricks
    restart: unless-stopped
    volumes:
      - /data/formbricks/sql:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -U formbricks -d formbricks || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  formbricks:
    image: ghcr.io/formbricks/formbricks
    container_name: formbricks
    depends_on:
      db:
        condition: service_healthy
    environment:
      WEBAPP_URL: https://${DOMAIN}
      DATABASE_URL: postgresql://formbricks:${SQL_PASS}@db:5432/formbricks?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CRON_SECRET: ${CRON_SECRET}
      TELEMETRY_DISABLED: 1
      AZUREAD_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZUREAD_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZUREAD_TENANT_ID: ${AZURE_TENANT_ID}
      MAIL_FROM: ${MAIL_FROM}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE_ENABLED: ${SMTP_SECURE_ENABLED}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_VERIFICATION_DISABLED: 1
      PASSWORD_RESET_DISABLED: 1
      EMAIL_AUTH_DISABLED: 1
      SIGNUP_DISABLED: 1
      INVITE_DISABLED: 1
      SENTRY_IGNORE_API_RESOLUTION_ERROR: 1
      NEXT_PUBLIC_SENTRY_DSN: 0
    volumes:
      - /data/formbricks/uploads:/home/nextjs/apps/web/uploads:rw
    restart: unless-stopped
```

### Screenshots

Here is an example of what Microsoft Entra ID asks for regarding redirect URLs when configuring a Web Platform App:

![image](https://github.com/formbricks/formbricks/assets/164041490/9e14935b-5d9d-4bc6-a34c-8ff20c486762)

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

- OS: `NixOS 24.05 (Uakari)`
- Docker: `v24.0.9`
- Formbricks Image: `sha256:111d8546c3c74ec84e66faf8905bae0bfc5c618b5104998cd678411c797d9bef`
