### ISSUE TITLE
400 bad request with message "url" parameter is not allowed on requests to host/_next/image?url=

### ISSUE THREAD

**Issue by helmstedt** [formbricks/formbricks#4336]
### Issue Summary

On a fresh install following the guide at https://formbricks.com/docs/self-hosting/docker and using Traefik, uploaded images are not loaded in the browser.

Inspecting the browser's traffic, I can see that I'm getting a "400 Bad Request" error on requests to urls like:

http://subdomain.domain.org/_next/image?url=http://subdomain.domain.org/storage/cm3oen449000810id8pv424zc/public/Digi_DT1--fid--8551fd4d-03f1-400a-be1d-2105741108af.jpg&w=256&q=75

The response content is **"url" parameter is not allowed**.

I can access the image itself using http://subdomain.domain.org/storage/cm3oen449000810id8pv424zc/public/Digi_DT1--fid--8551fd4d-03f1-400a-be1d-2105741108af.jpg without issues.

I am hosting Formbricks with Traefik running on http (not https!) on Ubuntu 24.04 with Docker Compose.

I am running the newest Formbricks docker image.

### Expected Behavior

I would expect images to be able to load.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

I have not tested on another server, but since I'm running with very basic configuration options, I suspect that this can be reproduced on any Formbricks http instance (it may behave differently on https?). I have attached my docker-compose.yml for Formbricks with Traefik labels:

[docker-compose.txt](https://github.com/user-attachments/files/17816405/docker-compose.txt)

### Your Environment

Self-hosted Formbricks

**Comment by mattinannt** [comment]
@helmstedt Thanks for raising an issue.
@pandeymangg Can you please look into this? :-)

**Comment by dhruv1707** [comment]
@helmstedt thanks for this!
Would you mind saying how you were able to route correctly to that subdomain.domain.org since in my current setup using your docker-compose.yml I am being routed to: https://www.domain.com/my-account/login

I have made the necessary changes in the codebase for your bug just need to check it once! :) 

Thanks

**Comment by helmstedt** [comment]
Thanks for looking at the issue. I don't think I'm doing anything special for routing, but I seem to be able to do everything (besides loading images) on my subdomain.domain.org and have not experienced being routed to an URL like you mention. When I visit http://subdomain.domain.org in a private browser with no cookies set, I get redirected to http://subdomain.domain.org/auth/login.

Besides my docker-compose.yml for Formbricks which I attached above (with secrets edited out and subdomain.domain.org as a placeholder), I have Traefik running with these settings:

```
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2

    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/traefik_access.log"

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

    restart: always

    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/:/logs/"
```
