### ISSUE TITLE
Unable to access Formbricks app - encryption key too long

### ISSUE THREAD

**Issue by WillEVTDigital** [formbricks/formbricks#5412]
### Issue Summary

I am unable to start Formbricks in Docker. All migrations apply successfully, but then it does not load with the following internal server error:

```
formbricks         | ❌ Invalid environment variables: [
formbricks         |   {
formbricks         |     code: 'too_big',
formbricks         |     maximum: 24,
formbricks         |     type: 'string',
formbricks         |     inclusive: true,
formbricks         |     exact: true,
formbricks         |     message: 'String must contain exactly 24 character(s)',
formbricks         |     path: [ 'FORMBRICKS_ENCRYPTION_KEY' ]
formbricks         |   }
formbricks         | ]
formbricks         | [Error: An error occurred while loading the instrumentation hook] {
formbricks         |   [cause]: Error: Invalid environment variables
formbricks         |       at o (.next/server/instrumentation.js:1:61472)
formbricks         |       at tl (.next/server/instrumentation.js:1:61647)
formbricks         |       at <unknown> (.next/server/instrumentation.js:1:61951)
formbricks         |       at 208595 (.next/server/instrumentation.js:1:62028)
formbricks         |       at t (.next/server/webpack-runtime.js:1:143)
formbricks         |       at 925440 (.next/server/instrumentation.js:1:72788)
formbricks         |       at t (.next/server/webpack-runtime.js:1:143)
formbricks         |       at 884356 (.next/server/instrumentation.js:1:72571)
formbricks         |       at t (.next/server/webpack-runtime.js:1:143)
formbricks         |       at <unknown> (.next/server/instrumentation.js:1:75359)
formbricks         | }
```

### Expected Behavior

Formbricks web app should load.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Image used: ghcr.io/formbricks/formbricks:latest

docker-compose:
```
  formbricksDB:
    container_name: formbricksDB
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    env_file: .env.development
    volumes:
      - formbricks-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${FORMBRICKS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${FORMBRICKS_DATABASE_PASSWORD}
      POSTGRES_DB: ${FORMBRICKS_DATABASE}
  formbricks:
    container_name: formbricks
    image: ghcr.io/formbricks/formbricks:latest
    restart: unless-stopped
    env_file: .env.development
    environment:
      WEBAPP_URL: ${FORMBRICKS_APP_URL}
      NEXTAUTH_URL: ${FORMBRICKS_APP_URL}
      DATABASE_URL: postgresql://${FORMBRICKS_DATABASE_USERNAME}:${FORMBRICKS_DATABASE_PASSWORD}@${FORMBRICKS_DATABASE_HOST}:5432/${FORMBRICKS_DATABASE}?schema=public
      NEXTAUTH_SECRET: ${FORMBRICKS_NEXTAUTH_SECRET}
      ENCRYPTION_KEY: ${FORMBRICKS_ENCRYPTION_KEY}
      CRON_SECRET: ${FORMBRICKS_CRON_SECRET}
      LOG_LEVEL: info
    ports:
      - "3300:1337"
    volumes:
      - formbricks-data:/app/data
    depends_on:
      - formbricksDB
```

.env.development:
```
#.... other vars...
# Formbricks
FORMBRICKS_APP_URL=http://localhost:3300
FORMBRICKS_NEXTAUTH_SECRET=_#64 char string_
FORMBRICKS_ENCRYPTION_KEY=_#64 char string_
FORMBRICKS_CRON_SECRET=_#64 char string_
FORMBRICKS_DATABASE=formbricks
FORMBRICKS_DATABASE_HOST=formbricksDB
FORMBRICKS_DATABASE_USERNAME=formbricks
FORMBRICKS_DATABASE_PASSWORD=formbricks
```

Encryption key generated using `openssl rand -hex 32` is 64 characters long

### Your Environment

Self-hosted Formbricks
