### ISSUE TITLE
"Page not found" after signup + unable to login

### ISSUE THREAD

**Issue by tigerblue77** [formbricks/formbricks#5522]
### Issue Summary

When deploying Formbricks Docker container for the first time, I go to http://localhost:3000 for the first time, it redirects me to http://localhost:3000/setup/signup then I sign up, the page reloads and shows (URL unchanged) :

![Image](https://github.com/user-attachments/assets/a9e045a6-470a-410b-ac66-478315042c94)

Then I go again to http://localhost:3000, try to sign in but the page just reloads itself ; no login happens, no error message, nothing.
Only this error log in the Docker container log :

> 2025/04/19 01:44PM ERR | pid=1 hostname=7a160db85394 name=formbricks err={"type":"RangeError","message":"Invalid key length","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:3)\n    at new Cipheriv (node:internal/crypto/cipher:234:3)\n    at Object.createCipheriv (node:crypto:143:10)\n    at E (/home/nextjs/apps/web/.next/server/chunks/2381.js:1:40366)\n    at _ (/home/nextjs/apps/web/.next/server/chunks/2381.js:1:41789)\n    at /home/nextjs/apps/web/.next/server/chunks/5316.js:2:1424\n    at async y (/home/nextjs/apps/web/.next/server/chunks/1044.js:11:161350)\n    at async next (/home/nextjs/apps/web/.next/server/chunks/1044.js:11:160296)\n    at async y (/home/nextjs/apps/web/.next/server/chunks/1044.js:11:159694)","code":"ERR_CRYPTO_INVALID_KEYLEN"} msg=SERVER ERROR

### Expected Behavior

Be correctly redirected after registering.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Here is the Docker compose file I'm using (I customized yours which is so so, TBH, outdated and doesn't include Redis cache nor container healthchecks) and I'm deploying with Ansible (that's why there are some Jinja2 variable {{ XX }}) :

```yaml
services:
  database:
    container_name: {{ Formbricks_PostgreSQL_Docker_service_name }}
    image: pgvector/pgvector:pg17
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "{{ Formbricks_PostgreSQL_database_name }}", "-U", "{{ Formbricks_PostgreSQL_database_user_name }}"]
      interval: 10s # Default : 30s
      timeout: 30s # Default : 30s
      start_period: 0s # Default : 0s
      retries: 3 # Default : 3
    # logging:
    #   driver: "none"
    environment:
      PUID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      PGID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      TZ: "{{ server_time_zone }}"
      POSTGRES_DB: "{{ Formbricks_PostgreSQL_database_name }}"
      POSTGRES_USER: "{{ Formbricks_PostgreSQL_database_user_name }}"
      POSTGRES_PASSWORD: "{{ Formbricks_PostgreSQL_database_password }}"
    volumes:
      - {{ Formbricks_PostgreSQL_Docker_volume_name }}:/var/lib/postgresql/data:rw
      # - "{{ Formbricks_PostgreSQL_database_dump_file_destination_path }}:/docker-entrypoint-initdb.d/{{ Formbricks_PostgreSQL_database_dump_file_name }}:rw" # Restore Formbricks database automatically but bad idea as it applies to each container restart
    networks:
      - {{ Formbricks_Docker_network_name }}
      # - PostgreSQL_PGadmin
  
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   depends_on:
  #     - postgresql
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: {{ PGadmin_email }}
  #     PGADMIN_DEFAULT_PASSWORD: {{ PGadmin_password }}
  #   volumes:
  #      - PGadmin_data:/var/lib/pgadmin4/storage:rw
  #   ports:
  #     - "82:80"
  #   networks:
  #     - PostgreSQL_PGadmin

  database_cache:
    container_name: redis
    image: redis
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    # user: 1000:1000
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s # Default : 30s
      timeout: 30s # Default : 30s
      start_period: 0s # Default : 0s
      retries: 3 # Default : 3
    environment:
      PUID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      PGID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      TZ: "{{ server_time_zone }}"
    volumes:
      - "{{ Formbricks_Redis_Docker_volume_name }}:/data:rw"
    networks:
      - {{ Formbricks_Docker_network_name }}

  application:
    container_name: {{ Formbricks_Docker_service_name }}
    image: [ghcr.io/formbricks/formbricks](http://ghcr.io/formbricks/formbricks)
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.services.Formbricks_application.loadbalancer.server.port: 3000
        traefik.http.routers.Formbricks_application.service: Formbricks_application
        traefik.http.routers.Formbricks_application.rule: Host(`{{ Formbricks_FQDN }}`)
        traefik.http.routers.Formbricks_application.entrypoints: websecure
    restart: unless-stopped
    depends_on:
      - database
      - database_cache
      # Not working while it's in the spec : https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1
      # - database:
      #     condition: service_healthy
    healthcheck:
      # test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://localhost:3000"]
      test: ["CMD-SHELL", "curl --silent --head --retry 1 http://localhost:3000"]
      interval: 30s # Default : 30s
      timeout: 30s # Default : 30s
      start_period: 300s # Default : 0s
      retries: 3 # Default : 3
    environment:
      PUID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      PGID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      TZ: "{{ server_time_zone }}"
      ######################################################## REQUIRED ########################################################

      # The url of your Formbricks instance used in the admin panel
      # Set this to your public-facing URL, e.g., https://example.com/
      WEBAPP_URL: "https://{{ Formbricks_FQDN }}"

      # Required for next-auth. Should be the same as WEBAPP_URL
      NEXTAUTH_URL: "https://{{ Formbricks_FQDN }}"

      # PostgreSQL DB for Formbricks to connect to
      DATABASE_URL: "postgresql://{{ Formbricks_PostgreSQL_database_user_name }}:{{ Formbricks_PostgreSQL_database_password }}@database:5432/{{ Formbricks_PostgreSQL_database_name }}?schema=public"

      # NextJS Auth
      # @see: https://next-auth.js.org/configuration/options#nextauth_secret
      # You can use: `openssl rand -hex 32` to generate one
      NEXTAUTH_SECRET: "Formbricks"

      # Encryption Key is used for 2FA & Single use URLs for Link Surveys
      # You can use: $(openssl rand -hex 32) to generate one
      ENCRYPTION_KEY: "Formbricks"

      # API Secret for running cron jobs.
      # You can use: $(openssl rand -hex 32) to generate a secure one
      CRON_SECRET: "Formbricks"

      # Set the minimum log level(debug, info, warn, error, fatal)
      # LOG_LEVEL: info

      ############################################# OPTIONAL (ENTERPRISE EDITION) #############################################

      # Enterprise License Key (More info at: https://formbricks.com/docs/self-hosting/license)
      # Required to access Enterprise-only features
      # ENTERPRISE_LICENSE_KEY:

      ############################################# OPTIONAL (EMAIL CONFIGURATION) #############################################

      # Email Configuration
      # MAIL_FROM:
      # MAIL_FROM_NAME:
      # SMTP_HOST:
      # SMTP_PORT:
      # SMTP_USER:
      # SMTP_PASSWORD:
      # SMTP_AUTHENTICATED:

      # (Additional option for TLS (port 465) only)
      # SMTP_SECURE_ENABLED:

      # If set to 0, the server will accept connections without requiring authorization from the list of supplied CAs (default is 1).
      # SMTP_REJECT_UNAUTHORIZED_TLS: 0

      ############################################## OPTIONAL (APP CONFIGURATION) ##############################################

      # Set the below to 0 to enable Email Verification for new signups (will required Email Configuration)
      EMAIL_VERIFICATION_DISABLED: 1

      # Set the below to 0 to enable Password Reset (will required Email Configuration)
      PASSWORD_RESET_DISABLED: 1

      # Set the below to 1 to disable logins with email
      # EMAIL_AUTH_DISABLED:

      # Set the below to 1 to disable invites
      # INVITE_DISABLED:

      # Set the below if you want to ship JS & CSS files from a complete URL instead of the current domain
      # ASSET_PREFIX_URL:

      # Set the below to your Unsplash API Key for their Survey Backgrounds
      # UNSPLASH_ACCESS_KEY:

      # Set the below to 0 to disable cron jobs
      # DOCKER_CRON_ENABLED: 1

      # Set the below to your Survey Domain(default is WEBAPP_URL)
      # SURVEY_URL:

      # Configure Formbricks usage within Formbricks.
      #FORMBRICKS_API_HOST:
      #FORMBRICKS_ENVIRONMENT_ID:

      ################################################### OPTIONAL (STORAGE) ###################################################

      # Set the below to set a custom Upload Directory
      # UPLOADS_DIR:

      # Set S3 Storage configuration (required for the file upload in serverless environments like Vercel)
      # S3_ACCESS_KEY:
      # S3_SECRET_KEY:
      # S3_REGION:
      # S3_BUCKET_NAME:

      # Set a third party S3 compatible storage service endpoint like StorJ leave empty if you use Amazon S3
      # S3_ENDPOINT_URL=

      # Force path style for S3 compatible storage (0 for disabled, 1 for enabled)
      S3_FORCE_PATH_STYLE: 0

      ############################################# OPTIONAL (OAUTH CONFIGURATION) #############################################

      # Set the below from Cloudflare Turnstile if you want to enable turnstile in signups
      # TURNSTILE_SITE_KEY:
      # TURNSTILE_SECRET_KEY:

      # Set the below from GitHub if you want to enable GitHub OAuth
      # GITHUB_ID:
      # GITHUB_SECRET:

      # Set the below from Google if you want to enable Google OAuth
      # GOOGLE_CLIENT_ID:
      # GOOGLE_CLIENT_SECRET:

      # Set the below from Azure Active Directory Login if you want to enable Azure AD OAuth
      # AZUREAD_CLIENT_ID:
      # AZUREAD_CLIENT_SECRET:
      # AZUREAD_TENANT_ID:

      # Set the below to OpenID Connect Provider if you want to enable OIDC
      # OIDC_CLIENT_ID:
      # OIDC_CLIENT_SECRET:
      # OIDC_ISSUER:
      # OIDC_DISPLAY_NAME:
      # OIDC_SIGNING_ALGORITHM:

      # Set the below to SAML Provider if you want to enable SAML
      # SAML_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/formbricks-saml?sslmode=disable"

      ########################################## OPTIONAL (THIRD PARTY INTEGRATIONS) ###########################################

      # Oauth credentials for Notion Integration
      # NOTION_OAUTH_CLIENT_ID:
      # NOTION_OAUTH_CLIENT_SECRET:

      # Oauth credentials for Google Sheet Integration
      # GOOGLE_SHEETS_CLIENT_ID:
      # GOOGLE_SHEETS_CLIENT_SECRET:
      # GOOGLE_SHEETS_REDIRECT_URL:

      # Oauth credentials for Airtable Integration
      # AIRTABLE_CLIENT_ID:

      # Oauth credentials for Slack Integration
      # SLACK_CLIENT_ID:
      # SLACK_CLIENT_SECRET:

      ############################################### OPTIONAL (LEGAL INFORMATION) ################################################

      # Set the below to have your own Privacy Page URL on auth & link survey page
      # PRIVACY_URL:

      # Set the below to have your own Terms Page URL on auth & link survey page
      # TERMS_URL:

      # Set the below to have your own Imprint Page URL on auth & link survey page
      # IMPRINT_URL:

      # Set the below to have your own Address on email footer
      # IMPRINT_ADDRESS:

      ########################################## OPTIONAL (SERVER CONFIGURATION) ###########################################

      # Set the below to 1 to disable Rate Limiting across Formbricks
      # RATE_LIMITING_DISABLED: 1

      # Set the below to send OpenTelemetry data for tracing
      # OPENTELEMETRY_LISTENER_URL: http://localhost:4318/v1/traces

      # Set the below to use Redis for Next Caching (default is In-Memory from Next Cache)
      REDIS_URL: "redis://database_cache:6379"
      REDIS_DEFAULT_TTL: 3600

      # Set the below to use for Rate Limiting (default us In-Memory LRU Cache)
      # REDIS_HTTP_URL:

      ############################################# OPTIONAL (OTHER) #############################################

      # Set the below to automatically assign new users to a specific organization and role within that organization
      # Insert an existing organization id or generate a valid CUID for a new one at https://www.getuniqueid.com/cuid (e.g. cjld2cjxh0000qzrmn831i7rn)
      # (Role Management is an Enterprise feature)
      # DEFAULT_ORGANIZATION_ID:
      # DEFAULT_ORGANIZATION_ROLE: owner
    volumes:
      - {{ Formbricks_uploads_Docker_volume_name }}:/home/nextjs/apps/web/uploads/:rw
      - {{ Formbricks_SAML_connection_Docker_volume_name }}:/home/nextjs/apps/web/saml-connection:rw
    ports:
      - {{ Formbricks_Docker_container_port_to_expose }}:3000
    networks:
      - {{ Formbricks_Docker_network_name }}
      - {{ DMZ_Docker_network_name }}

volumes:
  {{ Formbricks_PostgreSQL_Docker_volume_name }}:
  {{ Formbricks_Redis_Docker_volume_name }}:
  {{ Formbricks_uploads_Docker_volume_name }}:
  {{ Formbricks_SAML_connection_Docker_volume_name }}:

networks:
  {{ Formbricks_Docker_network_name }}:
  # PostgreSQL_PGadmin:
  {{ DMZ_Docker_network_definition }}
```

### Your Environment

Self-hosted Formbricks
