### ISSUE TITLE
Webhooks auto deleting at docker restart and at random

### ISSUE THREAD

**Issue by vitusan** [formbricks/formbricks#5894]
### Issue Summary

Im running formbricks on a docker environment. The thing is, whenever the server instance reboots or the docker container is restarted, the configured webhooks disappear!

The configured integrations work. Google Sheets is integrated and working. Even after reboot/restart it works.

But webhooks are forgotten after a restart/reboot. 

Also, webhooks also stop and vanish at random while the container/server is operating. Don't see nothing weird in the container logs. No errors.

### Expected Behavior

To not self delete.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Formbricks V3.8.0

### Your Environment

Self-hosted Formbricks

**Comment by victorvhs017** [comment]
Hey @vitusan! Thank you for opening this issue.

I've tried in my Docker environment, and the webhooks persisted through rebooting. Let's try to debug this a bit further. Can you answer these questions, please?

- How are you setting up your Docker environment? Did you use our [one-click setup](https://formbricks.com/docs/self-hosting/setup/one-click), our [hosted image](https://github.com/formbricks/formbricks/pkgs/container/formbricks), or are you running the [docker compose from the project directly](https://formbricks.com/docs/self-hosting/setup/docker)?
- If running directly, are you using the docker-compose.yml or the docker-compose.dev.yml file?
- If you are hosting it somewhere, which service are you using?
- How are you creating your webhooks? Through the UI, API v1 or API v2?

**Comment by mattinannt** [comment]
@vitusan Do you have an update on the questions @victorvhs017  had? :-)

**Comment by vitusan** [comment]
Sorry guys, time is short around here. So let me answer:

I'm hosting formbricks at a vps that's running coolify as the infra service.

I'm creating the webhooks through the UI. 

Do you guys need logs? Is there a log dump created by formbricks that i can attach here?

**Comment by victorvhs017** [comment]
@vitusan It seems that Coolify was having an issue that resembles the behavior you described https://github.com/coollabsio/coolify/issues/5099

Could you try to update your Coolify and your Formbricks version and see if that fixes the issue? I also recommend that you raise an issue on the Coolify GitHub if the problem persists

**Comment by jobenjada** [comment]
@victorvhs017 pls clarify the state of this bug / fix

**Comment by victorvhs017** [comment]
@jobenjada, we are waiting for the user feedback regarding the suggested fixes above.

**Comment by vitusan** [comment]
Hello, fellow d3vs!

Well, i have updated coolify to the latest version, and i also have updated formbricks to the latest version.

Things are working now.

Furthermore, i have discovered a bug, sort of, in coolify's docker compose template. The permanent storage is missconfigured. The env variable name is outdated/wrong, and there's a permission error regarding the formbricks user inside the container and the overall root/docker user in the machine.

I had to correct the env that controls the path to data storage and manually change permissions on the data folder docker created/linked at the specified path.

As i couldn't automate the storage solution permissions setting step, i haven't opened a PR to fix the template. I'm not very docker/shell proficient 😅.

**Comment by jobenjada** [comment]
@gupta-piyush19 please join the Coolify community and assure that our template gets fixed, you might be able to fix it yourself :)

**Comment by gupta-piyush19** [comment]
Hi @vitusan, thanks for pointing out the issues in the Formbricks template. I looked at it this week, but faced a few difficulties setting up the instance. I’ll check it again soon, probably next week. Could you also share what changes you made to the template while fixing the issue?

**Comment by vitusan** [comment]
Hello there @gupta-piyush19! Here's my compose:

```
services:
  formbricks:
    image: 'ghcr.io/formbricks/formbricks:latest'
    environment:
      - SERVICE_FQDN_FORMBRICKS_3000
      - WEBAPP_URL=$SERVICE_FQDN_FORMBRICKS
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgresql:5432/${POSTGRESQL_DATABASE:-formbricks}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - NEXTAUTH_SECRET=$SERVICE_BASE64_NEXTAUTH
      - NEXTAUTH_URL=$SERVICE_FQDN_FORMBRICKS
      - ENCRYPTION_KEY=$SERVICE_BASE64_ENCRYPTION
      - CRON_SECRET=$SERVICE_BASE64_CRON
      - 'ENTERPRISE_LICENSE_KEY=${ENTERPRISE_LICENSE_KEY}'
      - 'MAIL_FROM=${MAIL_FROM:-test@example.com}'
      - 'SMTP_HOST=${SMTP_HOST:-test.example.com}'
      - 'SMTP_PORT=${SMTP_PORT:-587}'
      - 'SMTP_USER=${SMTP_USER:-test}'
      - 'SMTP_PASSWORD=${SMTP_PASSWORD:-test}'
      - 'SMTP_SECURE_ENABLED=${SMTP_SECURE_ENABLED:-0}'
      - 'SMTP_REJECT_UNAUTHORIZED_TLS=${SMTP_REJECT_UNAUTHORIZED_TLS:-1}'
      - 'SHORT_URL_BASE=${SHORT_URL_BASE}'
      - 'EMAIL_VERIFICATION_DISABLED=${EMAIL_VERIFICATION_DISABLED:-1}'
      - 'PASSWORD_RESET_DISABLED=${PASSWORD_RESET_DISABLED:-1}'
      - 'EMAIL_AUTH_DISABLED=${EMAIL_AUTH_DISABLED:-0}'
      - 'INVITE_DISABLED=${INVITE_DISABLED:-0}'
      - 'UPLOADS_DIR=${UPLOADS_DIR}'
      - 'UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}'
      - 'GITHUB_ID=${GITHUB_ID}'
      - 'GITHUB_SECRET=${GITHUB_SECRET}'
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - 'AZUREAD_CLIENT_ID=${AZUREAD_CLIENT_ID}'
      - 'AZUREAD_CLIENT_SECRET=${AZUREAD_CLIENT_SECRET}'
      - 'AZUREAD_TENANT_ID=${AZUREAD_TENANT_ID}'
      - 'OIDC_CLIENT_ID=${OIDC_CLIENT_ID}'
      - 'OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}'
      - 'OIDC_ISSUER=${OIDC_ISSUER}'
      - 'OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}'
      - 'OIDC_SIGNING_ALGORITHM=${OIDC_SIGNING_ALGORITHM}'
      - 'NOTION_OAUTH_CLIENT_ID=${NOTION_OAUTH_CLIENT_ID}'
      - 'NOTION_OAUTH_CLIENT_SECRET=${NOTION_OAUTH_CLIENT_SECRET}'
      - 'GOOGLE_SHEETS_CLIENT_ID=${GOOGLE_SHEETS_CLIENT_ID}'
      - 'GOOGLE_SHEETS_CLIENT_SECRET=${GOOGLE_SHEETS_CLIENT_SECRET}'
      - 'GOOGLE_SHEETS_REDIRECT_URL=${GOOGLE_SHEETS_REDIRECT_URL}'
      - 'AIRTABLE_CLIENT_ID=${AIRTABLE_CLIENT_ID}'
      - 'SLACK_CLIENT_ID=${SLACK_CLIENT_ID}'
      - 'SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}'
      - 'PRIVACY_URL=${PRIVACY_URL}'
      - 'TERMS_URL=${TERMS_URL}'
      - 'IMPRINT_URL=${IMPRINT_URL}'
      - 'RATE_LIMITING_DISABLED=${RATE_LIMITING_DISABLED:-0}'
      - 'OPENTELEMETRY_LISTENER_URL=${OPENTELEMETRY_LISTENER_URL}'
      - 'REDIS_URL=${REDIS_URL}'
      - 'REDIS_HTTP_URL=${REDIS_HTTP_URL}'
      - 'DEFAULT_ORGANIZATION_ID=${DEFAULT_ORGANIZATION_ID}'
      - 'DEFAULT_ORGANIZATION_ROLE=${DEFAULT_ORGANIZATION_ROLE:-owner}'
    volumes:
      - 'formbricks-uploads:/apps/web/uploads/'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15
  postgresql:
    image: 'pgvector/pgvector:pg16'
    volumes:
      - 'formbricks-postgresql-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE:-formbricks}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

I had to tinker with folder ownership inside the container and assign the ownership to the formbricks user. Mostly chown commands.
